### ISSUE TITLE
Postgres not working

### ISSUE THREAD

**Issue by imaginepolis** [tabulaco/geotabuladb#1]
When trying to create a query using postgres, a connection terminated error is launched:

Error: Connection terminated
    at null.<anonymous> (/var/www/test_nodejs/test_libraries/node_modules/geotabuladb/node_modules/pg/lib/client.js:178:17)
    at g (events.js:180:16)
    at emit (events.js:92:17)
    at Socket.<anonymous> (/var/www/test_nodejs/test_libraries/node_modules/geotabuladb/node_modules/pg/lib/connection.js:66:10)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:466:12)
could not connect to postgres [Error: Connection terminated]

**Comment by vargax** [comment]
Solved long long time ago...
